use_frameworks!

platform :ios, '10.0'

target 'SPSwiftLog_Example' do
  pod 'SPSwiftLog', :path => '../'

  target 'SPSwiftLog_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
